workflows:
  android-workflow:
    environment:
      groups:
        - firebase
        - keystore_credentials
    name: Android Workflow
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Typescript
        script: |
          npm run build
          npx cap sync android
      - name: Decode keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
      - name: Sign APK
        script: |
          apksigner sign --ks $CM_KEYSTORE_PATH --ks-key-alias $CM_KEY_ALIAS --ks-pass pass:$CM_KEYSTORE_PASSWORD --key-pass pass:$CM_KEY_PASSWORD --out android/app/build/outputs/apk/release/app-release-signed.apk android/app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Verify Signed APK
        script: |
          apksigner verify --verbose --print-certs android/app/build/outputs/apk/release/app-release-signed.apk
      - name: Align APK
        script: |
          zipalign -v 4 android/app/build/outputs/apk/release/app-release-signed.apk android/app/build/outputs/apk/release/app-release-aligned.apk
          rm -rf android/app/build/outputs/apk/release/app-release-unsigned.apk
          rm -rf android/app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Verify Aligned APK
        script: |
          apksigner verify --verbose --print-certs android/app/build/outputs/apk/release/app-release-aligned.apk
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      firebase:
        # use this line to authenticate via service account
        firebase_service_account: $GOOGLE_APPLICATION_CREDENTIALS

        # or this line to authenticate via token:
        # firebase_token: $FIREBASE_TOKEN

        android:
          # Add your Android app id retrieved from Firebase console
          app_id: 1:761973486485:android:98f9b993fb008ebea07c9c
          # Add one or more groups that you wish to distribute your Android application to.
          # You can create groups in the Firebase console
          groups:
            - test