workflows:
  android-workflow:
    name: Android Workflow
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync android
      - name: Build Typescript
        script: |
          npm run build
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
          cd ..
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      scripts:
        - name: Load Firebase configuration
          script: |
            #!/usr/bin/env sh
            set -e # exit on first failed command
            
            echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/android/app/google-services.json
        - name: Distribute to Firebase App Distribution
          script: |
            # Instalar Firebase CLI
            curl -sL https://firebase.tools | bash
            # Configurar las credenciales de la cuenta de servicio
            echo $GOOGLE_APPLICATION_CREDENTIALS > service-account.json
            export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
            # Distribuir la app a Firebase App Distribution
            firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
              --app "1:761973486485:android:98f9b993fb008ebea07c9c" \
              --testers "josemanuel.chincho@codelorian.com" \
              --groups "testers" \
              --release-notes "Nueva versión de prueba para entorno de pruebas"
